name: Sync Garmin to Notion

on:
  schedule:
    # This cron job will run every 15 minutes from 6 AM to 11 PM Eastern Time
    # - cron: '*/10 10-23 * * *'  # Every 15 minutes from 10:00 to 23:45 UTC 
    # - cron: '*/10 0-3 * * *'    # Every 15 minutes from 00:00 to 03:45 UTC
    - cron: '0 1 * * *' # Daily
  workflow_dispatch:
env:
  TZ: 'America/Montreal'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run script
        env:
          GARMIN_EMAIL: ${{ secrets.laxlackey@gmail.com }}
          GARMIN_PASSWORD: ${{ secrets.)QQgNQ&yW89di3s }}
          NOTION_TOKEN: ${{ secrets.9eb4fd53-0e53-4183-999f-d401a0812670 }}
          NOTION_DB_ID: ${{ secrets.197ff25bed79817b9fcdd8667997b0b9?v=197ff25bed79817a9645000cda3ce1c2&pvs=4 }}
          NOTION_PR_DB_ID: ${{ secrets.197ff25bed7981599691c06d0e5acdea?v=197ff25bed798165afcc000ce51a260c&pvs=4 }}
          NOTION_STEPS_DB_ID: ${{ secrets.197ff25bed79816cb089d96d113b893c?v=197ff25bed7981c19c28000c9cd062a3&pvs=4 }}
          TZ: 'America/Montreal'
        run: |
          python garmin-activities.py
          python personal-records.py
          python daily-steps.py

